kevin-lee/effectie2-examples

- project/plugins.sbt
Upgrade: sbt-devoops `2.15.0` => `2.22.0`
> Upgrade: sbt-devoops 2.15.0 => 2.22.0

- project/plugins.sbt
Update: plugins.sbt - Add `sbt-devoops-starter`
> Update: plugins.sbt - Add sbt-devoops-starter

- build.sbt
- examples/effectie2-examples-cats-effect3/src/main/resources/logback.xml
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/MainApp.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/ExamplesRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/GreetingRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/JokeRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Jokes.scala
- examples/effectie2-examples-cats-effect3/src/test/scala-2/example/routes/ExamplesRoutesSpec.scala
Upgrade: libraries
- effectie 2.0.0-beta1 => 2.0.0-beta2
- logger-f 2.0.0-beta1 => 2.0.0-beta2
- refined: 0.9.28 => 0.10.1
- http4s 0.23.11 => 0.23.16
- circe 0.14.1 => 0.14.3
- logback 1.2.10 => 1.4.1
- hedgehog 0.8.0 => 0.9.0
- extras 0.13.0 => 0.19.0
> Upgrade: libraries

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
Use HTTP/2 for both server and client
> Use HTTP/2 for both server and client

- build.sbt
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/MainApp.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/ExamplesRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/JokeRoutes.scala
- examples/effectie2-examples-cats-effect3/src/test/scala-2/example/routes/ExamplesRoutesSpec.scala
Bump libraries - effectie, logger-f and extras
- effectie: 2.0.0-beta2 => 2.0.0-beta3
- logger-f: 2.0.0-beta2 => 2.0.0-beta3
- extras: 0.19.0 => 0.23.0
- extras-hedgehog-cats-effect3 => extras-hedgehog-ce3
> Bump libraries - effectie, logger-f and extras

- build.sbt
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/types.scala
> Update: Add kittens

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
Add: `withShutdownTimeout(1.second)`
> Add: `withShutdownTimeout(1.second)`

- build.sbt
Bump libraries: hedgehog 0.9.0 => 0.10.1 / extras 0.25.0 => 0.26.0
> Bump libraries: hedgehog 0.9.0 => 0.10.1 / extras 0.25.0 => 0.26.0

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/config/AppConfig.scala
Remove unnecessary `PortNumber.Value` type
> Remove unnecessary PortNumber.Value type

- build.sbt
- examples/effectie2-examples-cats-effect3/src/test/scala-2/example/routes/typesSpec.scala
> Adopt `hedgehog-extra`

- build.sbt
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/ExamplesRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Jokes.scala
Upgrade: `effectie` and `logger-f` to `2.0.0-beta4` and make changes accordingly
> Upgrade: effectie and logger-f to 2.0.0-beta4 and make changes accordingly

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/http4s/HttpClient.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Jokes.scala
- project/plugins.sbt
> Add: HttpClient

- build.sbt
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/http4s/HttpClient.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Example.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Jokes.scala
Bump libraries and sbt
- extras 0.27.0 => 0.28.0
- Add: extras-type-info
- Add: extras-render
- Add: extras-fs2-v3-text
> Bump libraries and sbt

- .scalafmt.conf
> Bump scalafmt 3.4.3 => 3.6.1

- .github/workflows/build.yml
> Update GitHub Actions config

- build.sbt
Bump libraries
- extras `0.32.0` => `0.33.0`
> Bump libraries

- build.sbt
Bump effectie, logger-f and extras
> Bump effectie, logger-f and extras

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/http4s/HttpClient.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/http4s/HttpError.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/routes/JokeRoutes.scala
- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/service/Jokes.scala
Add: more error handling with HttpError containing the request and the error from http4s
> Add: more error handling with HttpError containing the request and the error from http4s

- examples/effectie2-examples-cats-effect3/src/main/scala-2/example/ExamplesServer.scala
Update: Add `idleConnectionTime` to the `EmberClient`
> Update: Add idleConnectionTime to the EmberClient

- build.sbt
Upgrade libs
- hedgehog-extra to 0.4.0
- extras to 0.39.0
> Upgrade libs

- project/build.properties
> Bump sbt to 1.9.4
